@startuml

class Company {
    - id: int
    - companyname : String
    - country : String
}

class Employee {
    - id: int
    - firstname: String
    - lastname : String
    - phonenumber : String
    - email : String
    - salary : int
    - startdate : LocalDate
    - role : Role
    - company : Company
}

enum Role{
    COORDINATOR,
    DATA,
    ENGINEERING
}

Company "1" --* "0.." Employee
Employee . Role

@enduml